### ISSUE TITLE
Gemalto IDBridge K50 support

### ISSUE THREAD

**Issue by hexum** [OpenSC/openct#7]
Is [IDBridge K50](http://www.gemalto.com/Products/usb_shell_token_v3/index.html) supported by OpenSC?
I can't find any info on wiki.

**Comment by LudovicRousseau** [comment]
The IDBridge K50 is just a smart card reader. If the card inserted in the reader (SIM card format) is supported by OpenSC then it should work.

I note that I do not yet have the IDBridge K50 in my list. Can you follow https://pcsclite.alioth.debian.org/ccid.html#CCID_compliant please?

**Comment by hexum** [comment]
Sorry, I do not have a piece of hardware yet. Just looking for an appropriate one to buy.
I will return to this thread later.

**Comment by LudovicRousseau** [comment]
The Gemalto K50  device has the same USB idProduct 0x3437 as the Gemalto IDBridge CT30 and Gemalto PC Twin Reader.
This device should then be usable since CCID 0.1.0 (August 2003)

I added it in the "Should work but untested by me" list at https://pcsclite.alioth.debian.org/ccid/shouldwork.html#0x08E60x3437_1

So yes, your Gemalto K50 should work with OpenSC if the card inserted in the reader is supported by OpenSC.

**Comment by hexum** [comment]
Thank you!
